[tool.poetry]
name = "edm-classifier"
version = "0.1.0"
description = ""
authors = ["Ares <denon@xueyuan.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
xgboost = "^2.1.1"
numpy = "2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
